// Example API route showing Prisma usage (Prisma client will be generated by `prisma generate`)
import { PrismaClient } from "@prisma/client";

let prisma;
if (!global.prisma) {
  global.prisma = new PrismaClient();
}
prisma = global.prisma;

export default async function handler(req, res) {
  if (req.method === "GET") {
    const items = await prisma.item.findMany({ take: 20 });
    return res.status(200).json(items);
  }
  if (req.method === "POST") {
    const { title } = req.body;
    if (!title) return res.status(400).json({ error: "title required" });
    const item = await prisma.item.create({ data: { title } });
    return res.status(201).json(item);
  }
  res.setHeader("Allow", ["GET", "POST"]);
  res.status(405).end(`Method ${req.method} Not Allowed`);
}
